version: "3.3"
services:
  mssql:
    container_name: mssql
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes: 
      - "mssql_data:/var/opt/mssql"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sTroNk123Pass!!!
      - NAME=mssqldb
      - HOSTNAME=mssqldb
  redis:
    container_name: redis
    image: redis
    volumes:
     - "redis_data:/data"
     - "./redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
     - "7001:6379"
    restart: always
  todolist-aspnetcore-dockerized:
    container_name: todolist-aspnetcore-dockerized
    depends_on:
      - "mssql"
      - "redis"
    restart: always
    build: 
      context: .
      dockerfile: ./todolist-aspnetcore/Dockerfile
    ports:
      - "5005:5000"
volumes:
  mssql_data:
  redis_data: